"""Sklearn-compatible estimators for FSRE-ADATSK models."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, cast

import numpy as np
import numpy.typing as npt
import torch
from sklearn.utils.validation import check_is_fitted, validate_data

from ..memberships import ADATSKGaussianMF, GaussianMF, MembershipFunction
from ..models import (
    BaseTSK,
    FSREADATSKClassifierModel,
    FSREADATSKRegressorModel,
)
from ..optim._base import BaseTrainer
from ..optim._fsre import FSRETrainer
from ._base import (
    BatchSizeSpec,
    InputConfig,
    _BaseClassifierEstimator,
    _BaseRegressorEstimator,
)


class _ArticleMembership:
    """Fuzzy sets of the FSRE-AdaTSK article for the grid initialization.

    The article evaluates the memberships with ``exp(-(x - m)^2)`` (its Eq. 3), which has no
    spread, and places the centres evenly between the minimum and the maximum of each
    feature. Applied when the input configurations are generated by default.
    """

    input_configs: list[InputConfig] | None
    mf_init: Any

    def _resolve_input_configs(self, x: np.ndarray) -> list[InputConfig]:
        configs: list[InputConfig] = super()._resolve_input_configs(x)  # type: ignore[misc]
        if self.input_configs is not None:
            return configs
        n_mfs = getattr(self, "fs_n_mfs", None)
        return [
            InputConfig(name=cfg.name, n_mfs=int(n_mfs or cfg.n_mfs), overlap=cfg.overlap, margin=0.0)
            for cfg in configs
        ]

    def _build_input_mfs(self, x_arr: np.ndarray) -> tuple[Mapping[str, Sequence[MembershipFunction]], list[str], str]:
        input_mfs, feature_names, rule_base = super()._build_input_mfs(x_arr)  # type: ignore[misc]
        if self.mf_init != "grid" or self.input_configs is not None:
            return input_mfs, feature_names, rule_base
        article_mfs: dict[str, list[MembershipFunction]] = {
            name: [ADATSKGaussianMF(mean=float(cast(GaussianMF, mf).mean.detach()), sigma=1.0) for mf in mfs]
            for name, mfs in input_mfs.items()
        }
        return article_mfs, feature_names, rule_base


class FSREADATSKClassifier(_ArticleMembership, _BaseClassifierEstimator):
    """FSRE-ADATSK classifier with adaptive softmin antecedent and gated consequents.

    FSRE-ADATSK (Feature Selection and Rule Extraction) extends ADATSK.

    Reference:
        G. Xue, Q. Chang, J. Wang, K. Zhang and N. R. Pal, "An Adaptive
        Neuro-Fuzzy System With Integrated Feature Selection and Rule
        Extraction for High-Dimensional Classification Problems," in
        IEEE Transactions on Fuzzy Systems, vol. 31, no. 7, pp. 2167-2181,
        July 2023, doi: 10.1109/TFUZZ.2022.3220950.

    Example:
        ```python
        from highfis import FSREADATSKClassifier

        clf = FSREADATSKClassifier()
        clf.fit(X_train, y_train)
        ```
    """

    def __init__(
        self,
        *,
        lambda_init: float = 1.0,
        use_en_frb: bool = False,
        fs_n_mfs: int | None = None,
        re_n_mfs: int | None = None,
        gate_fn: str | None = "gate4",
        input_configs: list[InputConfig] | None = None,
        n_mfs: int = 3,
        mf_init: str = "grid",
        sigma_scale: float | str = 1.0,
        random_state: int | None = None,
        fs_epochs: int = 1000,
        re_epochs: int = 1000,
        finetune_epochs: int = 1000,
        learning_rate: float = 0.05,
        verbose: bool | int = False,
        rule_base: str | None = "coco",
        batch_size: BatchSizeSpec = "auto",
        shuffle: bool = True,
        ur_weight: float = 0.0,
        ur_target: float | None = None,
        consequent_batch_norm: bool = True,
        patience: int | None = 20,
        restore_best: bool = True,
        weight_decay: float = 1e-8,
        zeta_lambda: float = 0.5,
        zeta_theta: float = 0.3,
        structural_pruning: bool = True,
        trainer: BaseTrainer | None = None,
        device: str = "cpu",
        eval_metrics_every: int = 1,
        scheduler_class: type[Any] | None = None,
        scheduler_params: Mapping[str, Any] | None = None,
    ) -> None:
        """Initialise an FSRE-ADATSK classifier.

        Args:
            lambda_init: Accepted for API compatibility but not used by
                FSRE-ADATSK or DG-ALETSK.  FSRE-ADATSK computes its
                adaptive softmin index directly from membership values;
                DG-ALETSK uses the fixed exponent ``ξ = 700`` per
                paper eq. 22.  Default ``1.0``.
            fs_n_mfs: Number of fuzzy sets per feature in the feature-selection phase.
                ``None`` (default) uses ``n_mfs``. The source article uses 10.
            re_n_mfs: Number of fuzzy sets per feature in the rule-extraction phase, where
                the sets are rebuilt on an even grid over the selected features. ``None``
                (default) keeps the sets of the feature-selection phase. The source article
                uses 5.
            use_en_frb: Whether the feature-selection phase also runs on the enhanced rule
                base (En-FRB). The rule-extraction phase always does, as in the source
                article, where feature selection uses the compact rule base (CoCo-FRB):
                that is the default, ``False``.
            gate_fn: Gate function of the feature and rule gates, as a key of
                ``highfis.gates.GATE_FNS``. ``"gate4"`` (default) is the gate of the source
                article, ``λ sqrt(exp(1 - λ²))``. ``None`` gives ``ExpGate(k=10)``, the gate
                used before 0.32.0.
            input_configs: Per-feature InputConfig list. Only
                ``name`` is used when ``mf_init="kmeans"``.
            n_mfs: Number of fuzzy sets per feature (default ``3``).
            mf_init: ``"grid"`` (default) places the centres evenly between the minimum and the
                maximum of each feature, as in the source article. Also ``"kmeans"``,
                ``"minibatch_kmeans"`` and ``"fcm"``.
            sigma_scale: Sigma scale factor. ``1.0`` recommended.
            random_state: Seed for k-means and weight initialisation.
            fs_epochs: Epochs of phase 1, feature selection. Default ``1000``.
            re_epochs: Epochs of phase 2, rule extraction. Default ``1000``.
            finetune_epochs: Epochs of phase 3, fine-tuning. Default ``1000``.
            learning_rate: SGD learning rate (default ``0.05``). The family trains by plain
                full-batch gradient descent, so the rate and the number of epochs decide
                whether the gates open; the defaults were chosen by measurement, since the
                source article does not state the values of its main experiments.
            verbose: Print per-epoch progress.
            rule_base: ``"coco"`` (default, one rule per fuzzy set) or ``"cartesian"``.
            batch_size: Mini-batch size. ``"auto"`` (default) trains on the full batch, as in the
                source article. An integer sets the size and ``None`` is also the full batch.
            shuffle: Reshuffle each epoch.
            ur_weight: Weight of the uniform regularization (UR) term, a penalty on the deviation of
                each rule's average normalized firing strength from ``ur_target`` (Cui, Wu and Huang,
                2020). ``0.0`` disables the penalty.
            ur_target: Target average normalized firing strength of each rule. ``None`` uses ``1/R``,
                where ``R`` is the number of rules.
            consequent_batch_norm: Batch normalisation on consequent inputs.
                Default ``True``. Required for numerical stability: the
                first-order gated consequent spans all features and is optimized
                with plain gradient descent, which diverges (weights grow
                unbounded and become NaN) on high-dimensional data without this
                normalisation, collapsing the model to a single class. It is
                consistent with the CoCo-FRB TSK lineage the method builds on
                (Cui et al., 2020) and mirrors the ADATSK default. Set to
                ``False`` only for low-dimensional data where divergence does
                not occur.
            patience: Early-stopping patience (default ``20``). Set to ``None`` to disable early stopping.
                Early stopping needs a validation set passed to ``fit``; without one this has
                no effect.
            restore_best: If ``True`` (default), restore the best validation
                model weights after training.
                Has no effect unless a validation set is passed to ``fit``.
            weight_decay: L2 weight decay for consequent parameters.
            zeta_lambda: Feature-selection threshold coefficient (paper eq. 28).
                Larger values retain more features.  Default ``0.5``.
            zeta_theta: Rule-extraction threshold coefficient (paper eq. 29).
                Larger values retain more rules.  Default ``0.3``.
            structural_pruning: If ``True`` (default), hard-prune the model
                architecture after each threshold step.
            trainer: Optional custom BaseTrainer.
                When ``None`` (default) an FSRETrainer is built automatically
                from this estimator's hyperparameters.
            device: Target device for training and inference (e.g., ``"cpu"``,
                ``"cuda"``, or ``"mps"``).
            eval_metrics_every: Evaluate training metrics every ``n`` epochs; ``0``
                skips them. Each evaluation is an extra forward pass over the training
                set and only fills ``history_["train_<metric>"]``; early stopping uses
                validation metrics regardless.
            scheduler_class: Learning-rate scheduler *class* (e.g.
                ``torch.optim.lr_scheduler.StepLR``), not an instance -- the optimiser
                it must bind to is only built inside ``fit``.
            scheduler_params: Keyword arguments for ``scheduler_class``.

        Raises:
            ValueError: If ``lambda_init <= 0``.
        """
        self.lambda_init = lambda_init
        self.use_en_frb = use_en_frb
        self.fs_n_mfs = fs_n_mfs
        self.re_n_mfs = re_n_mfs
        self.gate_fn = gate_fn
        self.fs_epochs = fs_epochs
        self.re_epochs = re_epochs
        self.finetune_epochs = finetune_epochs
        self.zeta_lambda = zeta_lambda
        self.zeta_theta = zeta_theta
        self.structural_pruning = structural_pruning

        super().__init__(
            input_configs=input_configs,
            n_mfs=n_mfs,
            mf_init=mf_init,
            sigma_scale=sigma_scale,
            random_state=random_state,
            epochs=fs_epochs,
            learning_rate=learning_rate,
            verbose=verbose,
            rule_base=rule_base,
            batch_size=batch_size,
            shuffle=shuffle,
            ur_weight=ur_weight,
            ur_target=ur_target,
            consequent_batch_norm=consequent_batch_norm,
            patience=patience,
            restore_best=restore_best,
            weight_decay=weight_decay,
            device=device,
            eval_metrics_every=eval_metrics_every,
            scheduler_class=scheduler_class,
            scheduler_params=scheduler_params,
            trainer=trainer,
        )

    def fit(
        self,
        x: npt.ArrayLike,
        y: npt.ArrayLike,
        *,
        x_val: npt.ArrayLike | None = None,
        y_val: npt.ArrayLike | None = None,
        metrics: list[str] | None = None,
    ) -> FSREADATSKClassifier:
        """Fit the FSRE-ADATSK classifier estimator, checking lambda_init."""
        if self.lambda_init is not None and self.lambda_init <= 0.0:
            raise ValueError("lambda_init must be > 0")
        return cast(FSREADATSKClassifier, super().fit(x, y, x_val=x_val, y_val=y_val, metrics=metrics))

    def _build_model(
        self,
        input_mfs: Mapping[str, Sequence[MembershipFunction]],
        n_classes: int,
        rule_base: str,
        rules: Sequence[Sequence[int]] | None = None,
    ) -> BaseTSK:
        """Create FSREADATSKClassifierModel."""
        return FSREADATSKClassifierModel(
            input_mfs,
            n_classes=n_classes,
            rule_base=rule_base,
            rules=rules,
            consequent_batch_norm=bool(self.consequent_batch_norm),
            use_en_frb=self.use_en_frb,
            gate_fn=self.gate_fn,
        )

    def predict_proba(self, x: Any) -> np.ndarray:
        """Predict class probabilities, applying structural feature selection.

        When structural pruning was applied during fit(), the original
        feature matrix is automatically sliced to the surviving features before
        being passed to the pruned model.

        Args:
            x: Input array of shape ``(N, n_features_in_)``.

        Returns:
            Class probability array of shape ``(N, n_classes)``.
        """
        check_is_fitted(self, "model_")
        x_arr = validate_data(self, x, reset=False)
        history = getattr(self, "history_", None) or {}
        sf: list[int] | None = history.get("surviving_feature_indices")
        if sf is None and "threshold" in history:
            sf = history["threshold"].get("surviving_feature_indices")
        x_m = x_arr[:, sf] if sf is not None and cast(Any, self.model_).n_inputs < x_arr.shape[1] else x_arr
        device_str = str(self.device).lower()
        x_tensor = self._as_tensor_x(x_m, torch.device(device_str))
        probs = cast(Any, self.model_).predict_proba(x_tensor)
        return probs.detach().cpu().numpy()

    def __sklearn_tags__(self) -> Any:
        """Mark as poor_score: FSRE-ADATSK is designed for high-dimensional feature selection."""
        tags = super().__sklearn_tags__()
        tags.classifier_tags.poor_score = True
        return tags

    def _get_trainer(self) -> BaseTrainer:
        """Return an FSRETrainer built from this estimator's parameters."""
        return FSRETrainer(
            re_n_mfs=self.re_n_mfs,
            fs_epochs=self.fs_epochs,
            fs_learning_rate=float(self.learning_rate),
            fs_batch_size=self._effective_batch_size,
            fs_shuffle=bool(self.shuffle),
            fs_patience=self.patience,
            fs_weight_decay=float(self.weight_decay),
            fs_ur_weight=float(self.ur_weight),
            fs_ur_target=self.ur_target,
            re_epochs=self.re_epochs,
            re_learning_rate=float(self.learning_rate),
            re_batch_size=self._effective_batch_size,
            re_shuffle=bool(self.shuffle),
            re_patience=self.patience,
            re_weight_decay=float(self.weight_decay),
            re_ur_weight=float(self.ur_weight),
            re_ur_target=self.ur_target,
            finetune_epochs=self.finetune_epochs,
            finetune_learning_rate=float(self.learning_rate),
            finetune_batch_size=self._effective_batch_size,
            finetune_shuffle=bool(self.shuffle),
            finetune_patience=self.patience,
            finetune_restore_best=bool(self.restore_best),
            finetune_weight_decay=float(self.weight_decay),
            finetune_ur_weight=float(self.ur_weight),
            finetune_ur_target=self.ur_target,
            zeta_lambda=float(self.zeta_lambda),
            zeta_theta=float(self.zeta_theta),
            structural_pruning=bool(self.structural_pruning),
            verbose=self.verbose,
            eval_metrics_every=self.eval_metrics_every,
            scheduler_class=self.scheduler_class,
            scheduler_params=self.scheduler_params,
        )


class FSREADATSKRegressor(_ArticleMembership, _BaseRegressorEstimator):
    """FSRE-ADATSK regressor with adaptive softmin antecedent and gated consequents.

    FSRE-ADATSK (Feature Selection and Rule Extraction) extends ADATSK.

    Reference:
        G. Xue, Q. Chang, J. Wang, K. Zhang and N. R. Pal, "An Adaptive
        Neuro-Fuzzy System With Integrated Feature Selection and Rule
        Extraction for High-Dimensional Classification Problems," in
        IEEE Transactions on Fuzzy Systems, vol. 31, no. 7, pp. 2167-2181,
        July 2023, doi: 10.1109/TFUZZ.2022.3220950.

    Example:
        from highfis import FSREADATSKRegressor

        reg = FSREADATSKRegressor()
        reg.fit(X_train, y_train)
    """

    def __init__(
        self,
        *,
        lambda_init: float = 1.0,
        use_en_frb: bool = False,
        fs_n_mfs: int | None = None,
        re_n_mfs: int | None = None,
        gate_fn: str | None = "gate4",
        input_configs: list[InputConfig] | None = None,
        n_mfs: int = 3,
        mf_init: str = "grid",
        sigma_scale: float | str = 1.0,
        random_state: int | None = None,
        fs_epochs: int = 1000,
        re_epochs: int = 1000,
        finetune_epochs: int = 1000,
        learning_rate: float = 0.05,
        verbose: bool | int = False,
        rule_base: str | None = "coco",
        batch_size: BatchSizeSpec = "auto",
        shuffle: bool = True,
        ur_weight: float = 0.0,
        ur_target: float | None = None,
        consequent_batch_norm: bool = True,
        patience: int | None = 20,
        restore_best: bool = True,
        weight_decay: float = 1e-8,
        zeta_lambda: float = 0.5,
        zeta_theta: float = 0.3,
        structural_pruning: bool = True,
        trainer: BaseTrainer | None = None,
        device: str = "cpu",
        eval_metrics_every: int = 1,
        scheduler_class: type[Any] | None = None,
        scheduler_params: Mapping[str, Any] | None = None,
    ) -> None:
        """Initialise an FSRE-ADATSK regressor.

        Args:
            lambda_init: Accepted for API compatibility but not used by
                FSRE-ADATSK or DG-ALETSK.  FSRE-ADATSK computes its
                adaptive softmin index directly from membership values;
                DG-ALETSK uses the fixed exponent ``ξ = 700`` per
                paper eq. 22.  Default ``1.0``.
            fs_n_mfs: Number of fuzzy sets per feature in the feature-selection phase.
                ``None`` (default) uses ``n_mfs``. The source article uses 10.
            re_n_mfs: Number of fuzzy sets per feature in the rule-extraction phase, where
                the sets are rebuilt on an even grid over the selected features. ``None``
                (default) keeps the sets of the feature-selection phase. The source article
                uses 5.
            use_en_frb: Whether the feature-selection phase also runs on the enhanced rule
                base (En-FRB). The rule-extraction phase always does, as in the source
                article, where feature selection uses the compact rule base (CoCo-FRB):
                that is the default, ``False``.
            gate_fn: Gate function of the feature and rule gates, as a key of
                ``highfis.gates.GATE_FNS``. ``"gate4"`` (default) is the gate of the source
                article, ``λ sqrt(exp(1 - λ²))``. ``None`` gives ``ExpGate(k=10)``, the gate
                used before 0.32.0.
            input_configs: Per-feature InputConfig list. Only
                ``name`` is used when ``mf_init="kmeans"``.
            n_mfs: Number of fuzzy sets per feature (default ``3``).
            mf_init: ``"grid"`` (default) places the centres evenly between the minimum and the
                maximum of each feature, as in the source article. Also ``"kmeans"``,
                ``"minibatch_kmeans"`` and ``"fcm"``.
            sigma_scale: Sigma scale factor. ``1.0`` recommended.
            random_state: Seed for k-means and weight initialisation.
            fs_epochs: Epochs of phase 1, feature selection. Default ``1000``.
            re_epochs: Epochs of phase 2, rule extraction. Default ``1000``.
            finetune_epochs: Epochs of phase 3, fine-tuning. Default ``1000``.
            learning_rate: SGD learning rate (default ``0.05``). The family trains by plain
                full-batch gradient descent, so the rate and the number of epochs decide
                whether the gates open; the defaults were chosen by measurement, since the
                source article does not state the values of its main experiments.
            verbose: Print per-epoch progress.
            rule_base: ``"coco"`` (default, one rule per fuzzy set) or ``"cartesian"``.
            batch_size: Mini-batch size. ``"auto"`` (default) trains on the full batch, as in the
                source article. An integer sets the size and ``None`` is also the full batch.
            shuffle: Reshuffle each epoch.
            ur_weight: Weight of the uniform regularization (UR) term, a penalty on the deviation of
                each rule's average normalized firing strength from ``ur_target`` (Cui, Wu and Huang,
                2020). ``0.0`` disables the penalty.
            ur_target: Target average normalized firing strength of each rule. ``None`` uses ``1/R``,
                where ``R`` is the number of rules.
            consequent_batch_norm: Batch normalisation on consequent inputs.
                Default ``True``. Required for numerical stability: the
                first-order gated consequent spans all features and is optimized
                with plain gradient descent, which diverges (weights grow
                unbounded and become NaN) on high-dimensional data without this
                normalisation, collapsing the model to a single class. It is
                consistent with the CoCo-FRB TSK lineage the method builds on
                (Cui et al., 2020) and mirrors the ADATSK default. Set to
                ``False`` only for low-dimensional data where divergence does
                not occur.
            patience: Early-stopping patience (default ``20``). Set to ``None`` to disable early stopping.
                Early stopping needs a validation set passed to ``fit``; without one this has
                no effect.
            restore_best: If ``True`` (default), restore the best validation
                model weights after training.
                Has no effect unless a validation set is passed to ``fit``.
            weight_decay: L2 weight decay for consequent parameters.
            zeta_lambda: Feature-selection threshold coefficient (paper eq. 28).
                Larger values retain more features.  Default ``0.5``.
            zeta_theta: Rule-extraction threshold coefficient (paper eq. 29).
                Larger values retain more rules.  Default ``0.3``.
            structural_pruning: If ``True`` (default), hard-prune the model
                architecture after each threshold step.
            trainer: Optional custom BaseTrainer.
                When ``None`` (default) an FSRETrainer is built automatically
                from this estimator's hyperparameters.
            device: Target device for training and inference (e.g., ``"cpu"``,
                ``"cuda"``, or ``"mps"``).
            eval_metrics_every: Evaluate training metrics every ``n`` epochs; ``0``
                skips them. Each evaluation is an extra forward pass over the training
                set and only fills ``history_["train_<metric>"]``; early stopping uses
                validation metrics regardless.
            scheduler_class: Learning-rate scheduler *class* (e.g.
                ``torch.optim.lr_scheduler.StepLR``), not an instance -- the optimiser
                it must bind to is only built inside ``fit``.
            scheduler_params: Keyword arguments for ``scheduler_class``.

        Raises:
            ValueError: If ``lambda_init <= 0``.
        """
        self.lambda_init = lambda_init
        self.use_en_frb = use_en_frb
        self.fs_n_mfs = fs_n_mfs
        self.re_n_mfs = re_n_mfs
        self.gate_fn = gate_fn
        self.fs_epochs = fs_epochs
        self.re_epochs = re_epochs
        self.finetune_epochs = finetune_epochs
        self.zeta_lambda = zeta_lambda
        self.zeta_theta = zeta_theta
        self.structural_pruning = structural_pruning
        super().__init__(
            input_configs=input_configs,
            n_mfs=n_mfs,
            mf_init=mf_init,
            sigma_scale=sigma_scale,
            random_state=random_state,
            epochs=fs_epochs,
            learning_rate=learning_rate,
            verbose=verbose,
            rule_base=rule_base,
            batch_size=batch_size,
            shuffle=shuffle,
            ur_weight=ur_weight,
            ur_target=ur_target,
            consequent_batch_norm=consequent_batch_norm,
            patience=patience,
            restore_best=restore_best,
            weight_decay=weight_decay,
            device=device,
            eval_metrics_every=eval_metrics_every,
            scheduler_class=scheduler_class,
            scheduler_params=scheduler_params,
            trainer=trainer,
        )

    def _build_regressor_model(
        self,
        input_mfs: Mapping[str, Sequence[MembershipFunction]],
        rule_base: str,
        n_classes: int | None = None,
        rules: Sequence[Sequence[int]] | None = None,
    ) -> BaseTSK:
        """Create FSREADATSKRegressorModel."""
        return FSREADATSKRegressorModel(
            input_mfs,
            rule_base=rule_base,
            rules=rules,
            consequent_batch_norm=bool(self.consequent_batch_norm),
            use_en_frb=self.use_en_frb,
            gate_fn=self.gate_fn,
        )

    def __sklearn_tags__(self) -> Any:
        """Mark as poor_score: the regressor is an extension without a published reference.

        The source article only treats classification. On low-dimensional regression
        problems the regressor does not reach the accuracy of a linear model.
        """
        tags = super().__sklearn_tags__()
        tags.regressor_tags.poor_score = True
        return tags

    def predict(self, x: Any) -> np.ndarray:
        """Predict continuous targets, applying structural feature selection.

        When structural pruning was applied during fit(), the original
        feature matrix is automatically sliced to the surviving features before
        being passed to the pruned model.

        Args:
            x: Input array of shape ``(N, n_features_in_)``.

        Returns:
            Prediction array of shape ``(N,)``.
        """
        check_is_fitted(self, "model_")
        x_arr = validate_data(self, x, reset=False)
        history = getattr(self, "history_", None) or {}
        sf: list[int] | None = history.get("surviving_feature_indices")
        if sf is None and "threshold" in history:
            sf = history["threshold"].get("surviving_feature_indices")
        x_m = x_arr[:, sf] if sf is not None and cast(Any, self.model_).n_inputs < x_arr.shape[1] else x_arr
        device_str = str(self.device).lower()
        x_tensor = self._as_tensor_x(x_m, torch.device(device_str))
        preds = cast(Any, self.model_).predict(x_tensor)
        return preds.detach().cpu().numpy()

    def _get_trainer(self) -> BaseTrainer:
        """Return an FSRETrainer built from this estimator's parameters."""
        return FSRETrainer(
            re_n_mfs=self.re_n_mfs,
            fs_epochs=self.fs_epochs,
            fs_learning_rate=float(self.learning_rate),
            fs_batch_size=self._effective_batch_size,
            fs_shuffle=bool(self.shuffle),
            fs_patience=self.patience,
            fs_weight_decay=float(self.weight_decay),
            fs_ur_weight=float(self.ur_weight),
            fs_ur_target=self.ur_target,
            re_epochs=self.re_epochs,
            re_learning_rate=float(self.learning_rate),
            re_batch_size=self._effective_batch_size,
            re_shuffle=bool(self.shuffle),
            re_patience=self.patience,
            re_weight_decay=float(self.weight_decay),
            re_ur_weight=float(self.ur_weight),
            re_ur_target=self.ur_target,
            finetune_epochs=self.finetune_epochs,
            finetune_learning_rate=float(self.learning_rate),
            finetune_batch_size=self._effective_batch_size,
            finetune_shuffle=bool(self.shuffle),
            finetune_patience=self.patience,
            finetune_restore_best=bool(self.restore_best),
            finetune_weight_decay=float(self.weight_decay),
            finetune_ur_weight=float(self.ur_weight),
            finetune_ur_target=self.ur_target,
            zeta_lambda=float(self.zeta_lambda),
            zeta_theta=float(self.zeta_theta),
            structural_pruning=bool(self.structural_pruning),
            verbose=self.verbose,
            eval_metrics_every=self.eval_metrics_every,
            scheduler_class=self.scheduler_class,
            scheduler_params=self.scheduler_params,
        )

    def fit(
        self,
        x: npt.ArrayLike,
        y: npt.ArrayLike,
        *,
        x_val: npt.ArrayLike | None = None,
        y_val: npt.ArrayLike | None = None,
        metrics: list[str] | None = None,
    ) -> FSREADATSKRegressor:
        """Fit the FSRE-ADATSK regressor, checking lambda_init."""
        if self.lambda_init is not None and self.lambda_init <= 0.0:
            raise ValueError("lambda_init must be > 0")
        return cast(FSREADATSKRegressor, super().fit(x, y, x_val=x_val, y_val=y_val, metrics=metrics))
