"""Sklearn-compatible estimators for MHTSK models."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, Self

import numpy as np
import torch
from sklearn.utils.validation import check_X_y

from ..base import BaseTSK
from ..memberships import (
    MembershipFunction,
)
from ..models import (
    MHTSKClassifier,
    MHTSKRegressor,
)
from ._base import (
    InputConfig,
    _BaseClassifierEstimator,
    _BaseRegressorEstimator,
    _build_mhtsk_input_mfs,
    _extract_mhtsk_rule_indices,
    _extract_mhtsk_rule_indices_unsupervised,
    _resolve_mhtsk_scale_parameters,
)


class MHTSKClassifierEstimator(_BaseClassifierEstimator):
    """Estimator for the multihead Takagi-Sugeno-Kang fuzzy system.

    This estimator supports paper-derived automatic scale parameter resolution
    for head size and number of heads, and it optionally subsamples instances
    when building each head as described in the MHTSK paper.

    MHTSK builds multiple sparse subantecedents from random feature
    subsets and jointly optimizes their rule consequents.

    Reference:
        Z. Bian, Q. Chang, J. Wang and N. R. Pal, "Multihead
        Takagi-Sugeno-Kang Fuzzy System," in IEEE Transactions
        on Fuzzy Systems, vol. 33, no. 8, pp. 2561-2573, Aug. 2025,
        doi: 10.1109/TFUZZ.2025.3569227.

    Example:
        ```python
        from highfis import MHTSKClassifierEstimator

        clf = MHTSKClassifierEstimator()
        clf.fit(X_train, y_train)
        ```
    """

    def __init__(
        self,
        *,
        input_configs: list[InputConfig] | None = None,
        n_mfs: int = 3,
        n_heads: int | None = None,
        head_size: int | None = None,
        head_size_ratio: float | None = None,
        fcm_m: float = 2.0,
        rule_sigma: float = 1.0,
        fcr_target: float = 0.85,
        h_value: float | None = None,
        xi: float = 743.0,
        instance_sample_fraction: float = 0.8,
        rule_extraction: bool = False,
        crcr_us: float = 0.5,
        crcr_s: float = 0.5,
        retrain_after_extraction: bool = True,
        random_state: int | None = None,
        epochs: int = 10,
        learning_rate: float = 1e-2,
        verbose: bool | int = False,
        batch_size: int | None = 512,
        shuffle: bool = True,
        ur_weight: float = 0.0,
        ur_target: float | None = None,
        consequent_batch_norm: bool = False,
        patience: int | None = 20,
        restore_best: bool = True,
        weight_decay: float = 1e-8,
    ) -> None:
        """Initialize a MHTSK classifier estimator.

        Args:
            input_configs: Optional list of per-feature input configurations.
                Only the feature names are used for FCM-based MHTSK head construction.
            n_mfs: Number of FCM clusters per head (number of rules generated by each head).
            n_heads: Number of random heads. If ``None``, this is resolved from
                ``head_size`` together with ``fcr_target`` or ``h_value``.
            head_size: Number of features sampled per head. If ``None``, defaults to
                ``round(D * 0.02)`` for ``D <= 5000`` and ``round(D * 0.01)`` for larger inputs.
            head_size_ratio: Alternative relative head size, as a fraction of the input dimension.
            fcm_m: Fuzzification exponent for FCM cluster fitting.
            rule_sigma: Gaussian sigma applied to rule antecedent membership functions.
            fcr_target: Target feature coverage rate for randomly sampled heads.
            h_value: Paper-derived scale constant ``H`` used to compute the number of heads.
                When set, this overrides ``fcr_target``.
            xi: Numeric underflow threshold constant used to bound ``head_size``.
            instance_sample_fraction: Fraction of training instances sampled per head for FCM.
            rule_extraction: If ``True``, perform post-fit rule extraction (MHTSK_RE).
            crcr_us: Unsupervised cumulative rule contribution rate target used in extraction.
            crcr_s: Supervised cumulative rule contribution rate target used in extraction.
            retrain_after_extraction: If ``True``, retrain the extracted rule base after extraction.
            random_state: Random seed for reproducible head construction and FCM initialization.
            epochs: Maximum number of training epochs.
            learning_rate: Adam optimizer learning rate.
            verbose: Verbosity level during training.
            batch_size: Mini-batch size for gradient descent.
            shuffle: Whether to shuffle training samples each epoch.
            ur_weight: Weight of the uncertainty regularization term.
            ur_target: Target firing-level for uncertainty regularization.
            consequent_batch_norm: Apply batch normalization to the consequent layer inputs.
            patience: Early-stopping patience for validation.
            restore_best: Whether to restore the best validation model weights after training.
            weight_decay: Weight decay coefficient for the optimizer.
        """
        super().__init__(
            input_configs=input_configs,
            n_mfs=n_mfs,
            mf_init="fcm",
            sigma_scale=1.0,
            random_state=random_state,
            epochs=epochs,
            learning_rate=learning_rate,
            verbose=verbose,
            rule_base="custom",
            batch_size=batch_size,
            shuffle=shuffle,
            ur_weight=ur_weight,
            ur_target=ur_target,
            consequent_batch_norm=consequent_batch_norm,
            pfrb_max_rules=None,
            patience=patience,
            restore_best=restore_best,
            weight_decay=weight_decay,
        )
        self.n_heads = int(n_heads) if n_heads is not None else None
        self.head_size = int(head_size) if head_size is not None else None
        self.head_size_ratio = float(head_size_ratio) if head_size_ratio is not None else None
        self.fcm_m = float(fcm_m)
        self.rule_sigma = float(rule_sigma)
        self.fcr_target = float(fcr_target)
        self.h_value = float(h_value) if h_value is not None else None
        self.xi = float(xi)
        self.instance_sample_fraction = float(instance_sample_fraction)
        self.rule_extraction = bool(rule_extraction)
        self.crcr_us = float(crcr_us)
        self.crcr_s = float(crcr_s)
        self.retrain_after_extraction = bool(retrain_after_extraction)
        self._extracted_rule_indices_: list[int] | None = None

    def _build_input_mfs(self, x_arr: np.ndarray) -> tuple[Mapping[str, Sequence[MembershipFunction]], list[str], str]:  # type: ignore[override]
        feature_names = self._resolve_feature_names(x_arr)
        head_size, n_heads = _resolve_mhtsk_scale_parameters(
            n_features=x_arr.shape[1],
            head_size=self.head_size,
            head_size_ratio=self.head_size_ratio,
            n_heads=self.n_heads,
            fcr_target=self.fcr_target,
            h_value=self.h_value,
            sigma=self.rule_sigma,
            xi=self.xi,
        )
        input_mfs, rules, rule_feature_mask = _build_mhtsk_input_mfs(
            x_arr,
            feature_names=feature_names,
            n_heads=n_heads,
            head_size=head_size,
            n_clusters=int(self.n_mfs),
            fcm_m=self.fcm_m,
            rule_sigma=self.rule_sigma,
            instance_sample_fraction=self.instance_sample_fraction,
            random_state=self.random_state,
        )
        self._mhtsk_rules = rules
        self._mhtsk_rule_feature_mask = torch.as_tensor(rule_feature_mask, dtype=torch.bool)
        return input_mfs, feature_names, "custom"

    def _build_model(
        self,
        input_mfs: Mapping[str, Sequence[MembershipFunction]],
        n_classes: int,
        rule_base: str,
    ) -> BaseTSK:
        return MHTSKClassifier(
            input_mfs,
            self._mhtsk_rule_feature_mask,
            self._mhtsk_rules,
            n_classes=n_classes,
            consequent_batch_norm=bool(self.consequent_batch_norm),
        )

    def _build_extracted_model(
        self,
        input_mfs: Mapping[str, Sequence[MembershipFunction]],
        rule_indices: list[int],
    ) -> None:
        if not rule_indices:
            raise ValueError("At least one rule must be selected for extraction")
        self._mhtsk_rules = [self._mhtsk_rules[i] for i in rule_indices]
        self._mhtsk_rule_feature_mask = self._mhtsk_rule_feature_mask[rule_indices]
        self.model_ = self._build_model(input_mfs, len(self.classes_), self.rule_base_)

    def fit(self, x: Any, y: Any, *, x_val: Any | None = None, y_val: Any | None = None) -> Self:
        x_arr, y_arr = check_X_y(x, y)
        super().fit(x, y, x_val=x_val, y_val=y_val)

        if not bool(self.rule_extraction):
            return self

        x_t = self._as_tensor_x(x_arr)
        self.model_.eval()
        with torch.no_grad():
            norm_w = self.model_.forward_antecedents(x_t)

        y_t = torch.as_tensor(self._label_encoder_.transform(np.asarray(y_arr)), dtype=torch.long)
        selected = _extract_mhtsk_rule_indices(norm_w, y_t, self.crcr_us, self.crcr_s)
        self._extracted_rule_indices_ = selected

        input_mfs = self.model_.input_mfs
        self._build_extracted_model(input_mfs, selected)

        if self.retrain_after_extraction:
            x_val_t: torch.Tensor | None = None
            y_val_t: torch.Tensor | None = None
            if x_val is not None and y_val is not None:
                x_v_arr, y_v_arr = check_X_y(x_val, y_val)
                x_val_t = self._as_tensor_x(x_v_arr)
                y_val_t = torch.as_tensor(
                    self._label_encoder_.transform(np.asarray(y_v_arr)),
                    dtype=torch.long,
                )
            self.history_ = self.model_.fit(
                x_t,
                y_t,
                epochs=int(self.epochs),
                learning_rate=float(self.learning_rate),
                batch_size=self.batch_size,
                shuffle=bool(self.shuffle),
                ur_weight=float(self.ur_weight),
                ur_target=self.ur_target,
                verbose=self.verbose,
                x_val=x_val_t,
                y_val=y_val_t,
                patience=self.patience,
                restore_best=self.restore_best,
                weight_decay=float(self.weight_decay),
            )
        return self


class MHTSKRegressorEstimator(_BaseRegressorEstimator):
    """Estimator for the multihead Takagi-Sugeno-Kang fuzzy system.

    The regressor uses the same MHTSK head construction and scale parameter
    strategy as the classifier. Rule extraction is currently implemented with
    an unsupervised scheme only, since regression does not provide class labels
    for the Mann-Whitney based selection used in classification.

    MHTSK builds multiple sparse subantecedents from random feature
    subsets and jointly optimizes their rule consequents.

    Reference:
        Z. Bian, Q. Chang, J. Wang and N. R. Pal, "Multihead
        Takagi-Sugeno-Kang Fuzzy System," in IEEE Transactions
        on Fuzzy Systems, vol. 33, no. 8, pp. 2561-2573, Aug. 2025,
        doi: 10.1109/TFUZZ.2025.3569227.

    Example:
        ```python
        from highfis import MHTSKRegressorEstimator

        reg = MHTSKRegressorEstimator()
        reg.fit(X_train, y_train)
        ```
    """

    def __init__(
        self,
        *,
        input_configs: list[InputConfig] | None = None,
        n_mfs: int = 3,
        n_heads: int | None = None,
        head_size: int | None = None,
        head_size_ratio: float | None = None,
        fcm_m: float = 2.0,
        rule_sigma: float = 1.0,
        fcr_target: float = 0.85,
        h_value: float | None = None,
        xi: float = 743.0,
        instance_sample_fraction: float = 0.8,
        rule_extraction: bool = False,
        crcr_us: float = 0.5,
        retrain_after_extraction: bool = True,
        random_state: int | None = None,
        epochs: int = 10,
        learning_rate: float = 1e-2,
        verbose: bool | int = False,
        batch_size: int | None = 512,
        shuffle: bool = True,
        ur_weight: float = 0.0,
        ur_target: float | None = None,
        consequent_batch_norm: bool = False,
        patience: int | None = 20,
        restore_best: bool = True,
        weight_decay: float = 1e-8,
    ) -> None:
        """Initialize a MHTSK regressor estimator.

        Args:
            input_configs: Optional list of per-feature input configurations.
                Only the feature names are used for FCM-based MHTSK head construction.
            n_mfs: Number of FCM clusters per head (number of rules generated by each head).
            n_heads: Number of random heads. If ``None``, this is resolved from
                ``head_size`` together with ``fcr_target`` or ``h_value``.
            head_size: Number of features sampled per head. If ``None``, defaults to
                ``round(D * 0.02)`` for ``D <= 5000`` and ``round(D * 0.01)`` for larger inputs.
            head_size_ratio: Alternative relative head size, as a fraction of the input dimension.
            fcm_m: Fuzzification exponent for FCM cluster fitting.
            rule_sigma: Gaussian sigma applied to rule antecedent membership functions.
            fcr_target: Target feature coverage rate for randomly sampled heads.
            h_value: Paper-derived scale constant ``H`` used to compute the number of heads.
                When set, this overrides ``fcr_target``.
            xi: Numeric underflow threshold constant used to bound ``head_size``.
            instance_sample_fraction: Fraction of training instances sampled per head for FCM.
            rule_extraction: If ``True``, perform post-fit rule extraction.
            crcr_us: Unsupervised cumulative rule contribution rate target used in extraction.
            retrain_after_extraction: If ``True``, retrain the extracted rule base after extraction.
            random_state: Random seed for reproducible head construction and FCM initialization.
            epochs: Maximum number of training epochs.
            learning_rate: Adam optimizer learning rate.
            verbose: Verbosity level during training.
            batch_size: Mini-batch size for gradient descent.
            shuffle: Whether to shuffle training samples each epoch.
            ur_weight: Weight of the uncertainty regularization term.
            ur_target: Target firing-level for uncertainty regularization.
            consequent_batch_norm: Apply batch normalization to the consequent layer inputs.
            patience: Early-stopping patience for validation.
            restore_best: Whether to restore the best validation model weights after training.
            weight_decay: Weight decay coefficient for the optimizer.

        Notes:
            The regressor supports only unsupervised rule extraction via
            ``crcr_us`` because no label-based Mann-Whitney selection is available.
        """
        super().__init__(
            input_configs=input_configs,
            n_mfs=n_mfs,
            mf_init="fcm",
            sigma_scale=1.0,
            random_state=random_state,
            epochs=epochs,
            learning_rate=learning_rate,
            verbose=verbose,
            rule_base="custom",
            batch_size=batch_size,
            shuffle=shuffle,
            ur_weight=ur_weight,
            ur_target=ur_target,
            consequent_batch_norm=consequent_batch_norm,
            pfrb_max_rules=None,
            patience=patience,
            restore_best=restore_best,
            weight_decay=weight_decay,
        )
        self.n_heads = int(n_heads) if n_heads is not None else None
        self.head_size = int(head_size) if head_size is not None else None
        self.head_size_ratio = float(head_size_ratio) if head_size_ratio is not None else None
        self.fcm_m = float(fcm_m)
        self.rule_sigma = float(rule_sigma)
        self.fcr_target = float(fcr_target)
        self.h_value = float(h_value) if h_value is not None else None
        self.xi = float(xi)
        self.instance_sample_fraction = float(instance_sample_fraction)
        self.rule_extraction = bool(rule_extraction)
        self.crcr_us = float(crcr_us)
        self.retrain_after_extraction = bool(retrain_after_extraction)
        self._extracted_rule_indices_: list[int] | None = None

    def _build_input_mfs(self, x_arr: np.ndarray) -> tuple[Mapping[str, Sequence[MembershipFunction]], list[str], str]:  # type: ignore[override]
        feature_names = self._resolve_feature_names(x_arr)
        head_size, n_heads = _resolve_mhtsk_scale_parameters(
            n_features=x_arr.shape[1],
            head_size=self.head_size,
            head_size_ratio=self.head_size_ratio,
            n_heads=self.n_heads,
            fcr_target=self.fcr_target,
            h_value=self.h_value,
            sigma=self.rule_sigma,
            xi=self.xi,
        )
        input_mfs, rules, rule_feature_mask = _build_mhtsk_input_mfs(
            x_arr,
            feature_names=feature_names,
            n_heads=n_heads,
            head_size=head_size,
            n_clusters=int(self.n_mfs),
            fcm_m=self.fcm_m,
            rule_sigma=self.rule_sigma,
            instance_sample_fraction=self.instance_sample_fraction,
            random_state=self.random_state,
        )
        self._mhtsk_rules = rules
        self._mhtsk_rule_feature_mask = torch.as_tensor(rule_feature_mask, dtype=torch.bool)
        return input_mfs, feature_names, "custom"

    def _build_extracted_model(
        self,
        input_mfs: Mapping[str, Sequence[MembershipFunction]],
        rule_indices: list[int],
    ) -> None:
        if not rule_indices:
            raise ValueError("At least one rule must be selected for extraction")
        self._mhtsk_rules = [self._mhtsk_rules[i] for i in rule_indices]
        self._mhtsk_rule_feature_mask = self._mhtsk_rule_feature_mask[rule_indices]
        self.model_ = self._build_regressor_model(input_mfs, self.rule_base_, None)

    def fit(self, x: Any, y: Any, *, x_val: Any | None = None, y_val: Any | None = None) -> Self:
        x_arr, y_arr = check_X_y(x, y)
        super().fit(x, y, x_val=x_val, y_val=y_val)

        if not bool(self.rule_extraction):
            return self

        x_t = self._as_tensor_x(x_arr)
        self.model_.eval()
        with torch.no_grad():
            norm_w = self.model_.forward_antecedents(x_t)

        selected = _extract_mhtsk_rule_indices_unsupervised(norm_w, self.crcr_us)
        self._extracted_rule_indices_ = selected

        input_mfs = self.model_.input_mfs
        self._build_extracted_model(input_mfs, selected)

        if self.retrain_after_extraction:
            y_t = torch.as_tensor(np.asarray(y_arr), dtype=torch.float32)
            x_val_t: torch.Tensor | None = None
            y_val_t: torch.Tensor | None = None
            if x_val is not None and y_val is not None:
                x_v_arr, y_v_arr = check_X_y(x_val, y_val)
                x_val_t = self._as_tensor_x(x_v_arr)
                y_val_t = torch.as_tensor(np.asarray(y_v_arr, dtype=np.float32), dtype=torch.float32)
            self.history_ = self.model_.fit(
                x_t,
                y_t,
                epochs=int(self.epochs),
                learning_rate=float(self.learning_rate),
                batch_size=self.batch_size,
                shuffle=bool(self.shuffle),
                ur_weight=float(self.ur_weight),
                ur_target=self.ur_target,
                verbose=self.verbose,
                x_val=x_val_t,
                y_val=y_val_t,
                patience=self.patience,
                restore_best=self.restore_best,
                weight_decay=float(self.weight_decay),
            )
        return self

    def _build_regressor_model(
        self,
        input_mfs: Mapping[str, Sequence[MembershipFunction]],
        rule_base: str,
        n_classes: int | None = None,
    ) -> BaseTSK:
        return MHTSKRegressor(
            input_mfs,
            self._mhtsk_rule_feature_mask,
            self._mhtsk_rules,
            consequent_batch_norm=bool(self.consequent_batch_norm),
        )
