name: docs

on:
  push:
    branches:
      - dev
  release:
    types:
      - created

permissions:
  contents: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy-dev:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install git+https://github.com/squidfunk/mike.git

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy dev docs
        run: mike deploy --push dev

  deploy-release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install git+https://github.com/squidfunk/mike.git

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy release docs
        run: |
          FULL_TAG="${{ github.event.release.tag_name }}"
          VERSION="$(echo "$FULL_TAG" | grep -oP '^v\d+\.\d+')"
          VERSION="v${VERSION}"
          mike deploy --push --update-aliases $VERSION latest
